- hosts: all
  gather_facts: false

  tasks:
  - name: install pip
    apt:
      name: python3-pip
      state: present
    become: true 
  
  - name: install docker compose
    apt:
      name: docker-compose
      state: present
    become: true 
  
  - name: install docker python sdk
    pip:
      name: docker
      state: present
    become: true
  
  - name: copy the compose file
    copy:
      src: docker-compose.yml
      dest: /tmp/docker-compose.yml
    become: true
  
  - name: copy the prometheus configuration file
    copy:
      src: prometheus.yml
      dest: /home/config/prometheus.yml
    become: true

  - name: copy the filebeat configuration file
    copy:
      src: filebeat.yml
      dest: /home/config/filebeat.yml
    become: true

  - name: copying provisioning directory
    become: true
    copy:
      src: provisioning/
      dest: /home/config/provisioning

  - name: copy the generated .env file
    copy:
      src: .env
      dest: /home/config/.env
    become: true

  - name: Tear down existing services
    community.docker.docker_compose:
      project_src: /tmp/
      remove_images: all
      state: absent
    become: true

  - name: run the copied compose file
    community.docker.docker_compose:
      project_src: /tmp/
      state: present
    become: true

  - name: Restart a container
    community.docker.docker_container:
      name: myapplication
      image: "docker.elastic.co/beats/filebeat:7.17.1"
      command: filebeat -e -strict.perms=false
      user: root
      volumes:
        - filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
      state: started
      networks:
        - elk