filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
  multiline:
    type: pattern
    pattern: '^\['
    negate: true
    match: after

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["http://157.245.16.6:9200", "elasticsearch:9200"]
  username: 'kibana'
  password: 'sesame0uvr3toi'
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: docker.elastic.co/beats/filebeat:7.17.1
        - equals:
            container.image.name: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
        - equals:
            container.image.name: docker.elastic.co/kibana/kibana:7.17.1
    - index: "filebeat-minitwit-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
          - equals:
              container.image.name: mirbitu/minitwitimage:latest

logging.json: true
logging.metrics.enabled: false

