# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and Test

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f src/backend/requirements.txt ]; then pip install -r src/backend/requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          python -m pytest --import-mode=append src/backend/
  
  postman:

    jobs:
      automated-api-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install Postman CLI
            run: |
              curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          - name: Login to Postman CLI
            run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
          - name: Run API tests
            run: |
              postman collection run "8945217-6624a47c-3fc2-4136-ab89-df49655d926f"